# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [2]:
import numpy as np
import itertools

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    User can choose the dimension of matrix by himself (herself).
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix
a = int(input('Size: '))
the_matrix = random_matrix(a)
print(the_matrix)

def permutations(str):
    """
    The function creates the list of permutations for each string of the matrix.
    The number of the permutations equals n! (n-factorial), where n is a number of characters in each string.
    """
    ind = []
    for i in range(0,a):
        ind.append(i)
    k = list(itertools.permutations(ind, a))
    return k     
perm_res = permutations(the_matrix)    

def multiplex(mult):
    """
    The function creates the result list of product for elements with relevant indices.
    Element indices are selected according to the rule of permutations.
    """
    mult_list = []
    total = []
    mult_res = []
    N_list = []
    N_res = []
    l = 0
    for z in range(0,len(perm_res)):
        for y in range(0,a):    
            el = mult[y][perm_res[z][y]]
            mult_list.append(el)
    mult_res.append(mult_list[a:len(mult_list)-a])
    mult_res[0].reverse()
    mult_res.insert(0, mult_list[0:a])
    mult_res.insert(a, mult_list[len(mult_list)-a:len(mult_list)])
    final_list = [item for sub_list in mult_res for item in sub_list]  
    while l < len(final_list):    
        resul = np.prod(np.array(final_list[l:l+a]))
        total.append(resul)
        l += a 
    for coeff in perm_res:
        N = 0
        for c, d in itertools.combinations(coeff, 2):
            if c > d: 
                N += 1
        N_list.append(N)  
    N_res.append(N_list[1:len(total)-1])
    start = []
    start.append(N_list[len(total)-1])
    end = []
    end.append(N_list[0])
    N_res.insert(0,start)
    N_res.insert(len(total)-1,end)
    final_coeff_list = [item2 for sub_list2 in N_res for item2 in sub_list2] 
    final_coeff_list.reverse()     
    det_mult = list(map(lambda el1,el2: el1*(-1)**el2, total,final_coeff_list))    
    return det_mult

def summ(det):
    """
    This function summarizes all product results.
    The value of the summ function is the determinant value.
    """               
    det = sum(det)
    return det
print('\nThe determinant value: ',summ(multiplex(the_matrix)))    

[[0 1 9]
 [3 9 2]
 [0 6 1]]

The determinant value:  159
